### ISSUE TITLE
JPEGXSSubDescriptor 6th byte key value

### ISSUE THREAD

**Issue by puscas** [SMPTE/st2124#2]
Hi

I noticed the 6th byte of the key is 0x7F, but other sub descriptors use 0x53. This seems odd to me but probably I'm missing something.
It's possible to explain this decision ?

Thank you!

**Comment by IMFTool** [comment]
Byte 6 of the SubDescriptor Group UL is the Registry Designator.
It is typically registered with the value 0x7F as placeholder.
Per SMPTE ST 336, a value of 0x53 indicates two byte length field and two byte local tag encoding.

>> but other sub descriptors use 0x53
Can you provide pointers to engineering documents that have registered a value of 0x53 for byte 6 of SubDescriptor ULs?

**Comment by puscas** [comment]
Thanks for the quick answer!

I'm comparing against the JPEG2000 sub-descriptor: https://pub.smpte.org/latest/st422/st422-2022.pdf
And if I understood correctly, the Key used for JPEG2000 sub-descriptor is: `06 0E 2B 34 02 **53** 01 01 0D 01 01 01 01 01 5A 00` (as defined in section 8.2.2 )

**Comment by IMFTool** [comment]
The JPEG2000SubDescriptor as defined in ST 422 is registered in [1] as follows:
`      <Symbol>JPEG2000SubDescriptor</Symbol>
      <UL>urn:smpte:ul:060e2b34.027f0101.0d010101.01015a00</UL>
`
Again, 0x7f is a placeholder for the actual Registry Designator.

[1] https://registry.smpte-ra.org/view/published/Groups.xml

**Comment by puscas** [comment]
Now I got it! Thank you very much for the explanation.
